### ISSUE TITLE
How do I start using this?

### ISSUE THREAD

**Issue by ericop** [erikvullings/mithril-materialized#4]
Hi Erik,
This looks really cool, and I'm sure it's setup currently for your easy use, since you're .. well the main one using it. :) But for others new to trying to use it, if you could have more "step-by-step here's how to get going" it would be a great help. 

_Note: I realize this is cool stuff you're probably working on in your free time, but since it looks to beautiful if we can have docs for easy entry for new people to get up and running that would be sweet._ 

My current **mithril** setup is just an html with `link` and `script` tags. When I use other frameworks, like **preact**, **ember**, or **angular** I'm spoiled with a CLI that could easily pull in cool add-ons such as what you've built here, but I don't know of such a stream-lined start or yomen generator for mithril.  this means I must overcome an emotional hurdle to try and hand stictch such a solution together just to start being productive and try things out. (This may be because I'm new to the mithril community, and its set of ideals of light, simple and fast, but it feels like mithril had a missing piece here.)

---
- So I did end up just cloning this and running `npm install` and `npm run start`, but this lead to some

```
'parcel' is not recognized as an internal or external command, operable program or batch file
```

- Next I gave `npm install -g parcel-bundler` a try.  
- After I did `npm run start run` the server for localhost:1234 which seemed happy. but then I got

> 🚨 Build Error
>D:\src\test-idea\node_modules\mithril-materialized\dist\button.js:1:25: > Cannot resolve dependency 'tslib'

I hope this feedback has some value. My hope is that you continue to enjoy your code 🌟 🎩 wizardry 👨‍🏫   , and offering up neat stuff like this to the community. I really do appreciate folks like yourself trying to share your work with the world and to keep **mithril** modern and wired up with strong helper features. Keep it up!

**Comment by erikvullings** [comment]
@ericop Thanks for the feedback.

I've just checked the package.json files, and I believe they are correct. `parcel` and `tslib` are devDependencies, so they should have been installed. Did you follow the instructions in the README.md?

```console
npm i -g pnpm
pnpm m i
npm start
```
Should be all that is needed to first install `pnpm` globally (alternative to `npm`), run `pnpm` to install all packages (this is a mono-repo with two packages in the `packages` folder, the example project and the lib itself), and start it.

If you want a quick start, indeed, mithril does not have a CLI, but if you copy the `packages/example` folder to a new project folder, and run `pnpm i` and `npm start`, it should work. Running it separately, it will install the `mithril-materialized` lib from `npm` instead of linking it to `packages/lib`.

A few pointers: `layout.ts` contains the nav menu stuff. `dashboard-service.ts` is used for managing the pages and setting the routes (in `app.ts`). You should change the app title in `index.html`, create a new `favicon.ico` in the assets and root folder, and change the `git` repo, author name, etc. in `package.json`. If you run into any issues, let me know, and I'll try to help you.

**Comment by ericop** [comment]
@erikvullings thanks for the tip. I don't use pnpm so I didn't use that in my trial, but that might have been the missing link. Again it proves so weird that npm and pnpm have different results. I used to get the same thing with angular and other projects.

Thanks for explaining the layout a little bit too.

**Comment by ericop** [comment]
Today I just learned of [npm Inc. and Entropic](https://github.com/ceejbot/economics-of-package-management/blob/master/essay.md) so I may be jumping ship on traditional npm sooner than later..

**Comment by erikvullings** [comment]
Interesting read, albeit a bit too long. It could use a TLDR section at the start. Another alternative, btw, is github itself, which is doing something similar.

**Comment by rebootcode** [comment]
Is there non-npm version too? like just include "src" and done?

**Comment by erikvullings** [comment]
@rebootcode it is better to open a new issue, as this is another subject, but anyways, you can always get npm packages directly from unpkg. So in this case, it is: 
https://unpkg.com/mithril-materialized@0.13.15/dist/index.js
